In [8]:
! pip install numpy

In [7]:
import numpy as np

In [3]:
list=[1,2,3,4,5]

In [4]:
print(list)

[1, 2, 3, 4, 5]


In [5]:
# 1 d array 

In [6]:
a=np.array([1,2,3,4,5])

In [7]:
print(a)

[1 2 3 4 5]


In [8]:
# 2 d array

In [9]:
b=np.array([[1,2,3,4,5]
           ,[6,7,8,9,10]])

In [10]:
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
# 3 - d array

In [15]:
c=np.array([[[1,2,3,4,5]
           ,[6,7,8,9,10],
           [11,12,13,14,15]]])

In [16]:
print(c)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [17]:
type(a)

numpy.ndarray

In [18]:
# size

In [20]:
print(a.size)

5


In [21]:
print(b.size)


10


In [22]:
print(c.size)

15


In [23]:
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(2, 5)
(1, 3, 5)


In [24]:
# data  type

In [25]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


In [26]:
# transpose 

In [27]:
c.transpose()

array([[[ 1],
        [ 6],
        [11]],

       [[ 2],
        [ 7],
        [12]],

       [[ 3],
        [ 8],
        [13]],

       [[ 4],
        [ 9],
        [14]],

       [[ 5],
        [10],
        [15]]])

In [28]:
np.empty((4,4),dtype=int)

array([[25895968444448860, 23925768161198147, 32370111954616435,
        29555366483001436],
       [12948244068892717, 32651616996819049, 25896170311057512,
        28710924373327984],
       [26740556586287209, 27303510834217060, 25896196080664693,
        32651591226556520],
       [12948368627204207, 29555336418492531, 29836540811477108,
        30962737072111727]])

In [59]:
np.zeros((6,7,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
  

In [33]:
np.zeros((4,6),dtype=bool)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [60]:
np.zeros((3,6,7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [34]:
np.ones((6,7),dtype=str)

array([['1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1']], dtype='<U1')

In [ ]:
# arange

In [36]:
a=np.arange(1,20)

In [37]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [38]:
b=np.arange(1,20,2)

In [39]:
print(b)

[ 1  3  5  7  9 11 13 15 17 19]


In [64]:
c=np.arange(2,20,2)

In [65]:
print(c)

[ 2  4  6  8 10 12 14 16 18]


In [69]:
c.reshape((3,3))


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [70]:
a=np.arange(1,45)

In [71]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]


In [80]:
a.reshape((2,2,11))

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]],

       [[23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33],
        [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]]])

In [84]:
type(a)

numpy.ndarray

In [85]:
print(a.ndim)

1


In [43]:
c.flatten()

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
c.ravel()

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
a=np.arange(1,51)
a=a.reshape(10,5)
print(a)


NameError: name 'np' is not defined

# Assistant
The error occurs because you're trying to use the NumPy library (np) without importing it first. The "np" alias is commonly used for NumPy, but you need to import the library before you can use it.

Would you like me to provide the corrected code?

# User
yes

In [6]:
# Assistant
import numpy as np  # Add this line to import the NumPy library

a = np.arange(1, 51)
a = a.reshape(10, 5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [56]:
a[0]

array([1, 2, 3, 4, 5])

In [59]:
a[0,0]

np.int64(1)

In [60]:
a[2,4]

np.int64(15)

In [9]:
a[0:10]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [10]:
a[2:5,4]

array([15, 20, 25])

In [12]:
a=np.arange(0,18).reshape((6,3))

In [14]:
b=np.arange(20,38).reshape((6,3))

In [15]:
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [16]:
a+b

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [18]:
np.add(a,b)

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [19]:
b.argmax()

np.int64(17)

In [20]:
np.sum(b,axis=1)

array([ 63,  72,  81,  90,  99, 108])

In [26]:
np.sum(b,axis=0)

array([165, 171, 177])

In [22]:
np.multiply(a,b)

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [23]:
np.mean(b)

np.float64(28.5)

In [25]:
np.sqrt(b)

array([[4.47213595, 4.58257569, 4.69041576],
       [4.79583152, 4.89897949, 5.        ],
       [5.09901951, 5.19615242, 5.29150262],
       [5.38516481, 5.47722558, 5.56776436],
       [5.65685425, 5.74456265, 5.83095189],
       [5.91607978, 6.        , 6.08276253]])

In [27]:
np.divide(a,b)

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [28]:
np.subtract(a,b)

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [35]:
print(a)

[1 2 3 4 5 6 7]


In [39]:
a=np.arange(1,99)

In [40]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98]


In [42]:
np.empty((6,7),dtype=int)

array([[              0,   1766252897136,               0,
                      0,               1,               0,
                      0],
       [              0,               1,               0,
        140714372209040,               0,               0,
                      0],
       [              0,               0,               0,
                      0,               0,               0,
                      0],
       [              0,               0,               0,
                      0,               0,               0,
                      0],
       [              0,               0,               0,
                      0,               0,               0,
                      0],
       [              0,               0,               0,
                      0,               0,               0,
                      0]])

In [43]:
np.random.random(1)

array([0.8648863])

In [44]:
np.random.random(2)

array([0.84966175, 0.35797826])

In [52]:
np.random.random((2,2,3))

array([[[0.56000794, 0.31387885, 0.63211887],
        [0.44365697, 0.74636989, 0.89746951]],

       [[0.50332245, 0.93701489, 0.13253786],
        [0.29006059, 0.98538175, 0.62959745]]])

In [48]:
np.random.random((6,7,8))

array([[[0.01801423, 0.03247137, 0.79999369, 0.83012209, 0.27306408,
         0.67770488, 0.20270181, 0.8488307 ],
        [0.77052513, 0.24544562, 0.35484005, 0.10266784, 0.56038538,
         0.5950204 , 0.76497419, 0.4038139 ],
        [0.01380449, 0.1547883 , 0.87796729, 0.34616676, 0.71748598,
         0.99937584, 0.79358347, 0.70744431],
        [0.78518898, 0.90686125, 0.77987959, 0.57624954, 0.58662699,
         0.06174057, 0.84375494, 0.13276482],
        [0.44098756, 0.1316395 , 0.34543881, 0.76414329, 0.61604563,
         0.53214328, 0.81095841, 0.70425743],
        [0.56245984, 0.59556551, 0.94765518, 0.02720071, 0.94190454,
         0.42055786, 0.57118892, 0.34813092],
        [0.40365762, 0.29745997, 0.77457173, 0.30662859, 0.62988274,
         0.99231186, 0.46733064, 0.9551026 ]],

       [[0.33939879, 0.2724567 , 0.74292838, 0.183898  , 0.82814702,
         0.10296842, 0.41221327, 0.36786548],
        [0.51984216, 0.39720232, 0.08531874, 0.9708969 , 0.44945691,
         

In [49]:
np.random.randint(1,10)

4

In [51]:
np.random.randint(1,10,(3,4,5))

array([[[8, 3, 2, 7, 6],
        [1, 9, 2, 3, 5],
        [1, 4, 3, 1, 4],
        [8, 4, 5, 4, 1]],

       [[2, 5, 2, 6, 7],
        [1, 9, 8, 3, 5],
        [5, 6, 6, 1, 8],
        [8, 2, 3, 1, 2]],

       [[9, 7, 5, 3, 3],
        [6, 3, 4, 5, 1],
        [2, 8, 5, 9, 4],
        [6, 9, 6, 1, 9]]], dtype=int32)

In [53]:
a="my name is anup"
b="i am a good boy"

In [54]:
np.char.add(a,b)

np.str_('my name is anupi am a good boy')

In [55]:
np.char.lower(a)

array('my name is anup', dtype='<U15')

In [56]:
np.char.upper(b)

array('I AM A GOOD BOY', dtype='<U15')

In [86]:
np.random.randint(1,10)

3

In [87]:
np.random.randint(1,10,(2,4))

array([[4, 4, 8, 9],
       [9, 3, 1, 6]], dtype=int32)

In [89]:
np.random.randint(1,10,(5,4,3))

array([[[4, 4, 3],
        [4, 8, 4],
        [5, 1, 1],
        [3, 6, 2]],

       [[2, 4, 8],
        [3, 4, 6],
        [7, 1, 5],
        [2, 2, 2]],

       [[5, 7, 3],
        [2, 7, 8],
        [1, 2, 5],
        [6, 3, 8]],

       [[8, 8, 5],
        [6, 2, 3],
        [5, 9, 4],
        [2, 2, 8]],

       [[5, 4, 9],
        [1, 1, 7],
        [6, 1, 3],
        [5, 9, 9]]], dtype=int32)